# Generated by Django 5.0.2 on 2024-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
